✨ Introduce a global New() selecting the type depending on URL pattern
teal-finance/notifier pull request #5
Opened 2022-08-18 08:05 UTC by 0uep

2022-08-21 20:04 UTC, olibre approved these changes

2022-08-25 10:07 UTC, kahlys commented
To _magical_ for me

2022-08-26 10:11 UTC, 0uep commented
> To _magical_ for me

When other notification technologies will be supported (e.g. Telegram, Twitter, Signal…) we will be able to detect from the endpoint pattern what Notifier implementation to use: MattermostNotifier, TelegramNotifier, TwitterNotifier, SignalNotifier... and the LoggerNotifier as fallback. That's it.

2022-10-30 10:34 UTC, kahlys requested changes
I don't really like it, because it can have multiple arguments, not only a endpoint (like tokens, etc).
Maybe we can do something like the `sql`  package do with `datasourcename` as a string.

2022-10-30 10:40 UTC, closed without merging